[package]
name = "dirt2-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
dirt2-common = { path = "../dirt2-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "dirt2"
path = "src/main.rs"
